# Generated by Django 5.1.2 on 2024-10-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("Indeed", "Indeed"),
                            ("GlassDoor", "GlassDoor"),
                            ("Naukri", "Naukri"),
                        ],
                        max_length=20,
                    ),
                ),
                ("jobsearch", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("pages", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
